import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import Layout from "../components/Layout";
import {
  forecast as apiForecast,
  downloadCsv,
  getAlerts,
  getReport,
} from "../api";
import ForecastChart from "../components/ForecastChart";

export default function Dashboard() {
  const token = localStorage.getItem("token");
  const [file, setFile] = useState<File | null>(null);
  const [horizon, setHorizon] = useState(4);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [alerts, setAlerts] = useState<any[] | null>(null);
  const [report, setReport] = useState<string | null>(null);
  const [reportLoading, setReportLoading] = useState(false);
  const [email, setEmail] = useState("");
  const navigate = useNavigate();
  if (!token) navigate("/login");
  const [activeTab, setActiveTab] = useState<"results" | "alerts" | "report">(
    "results"
  );

  // Derived overview stats and category summary based on forecast results
  const overview = React.useMemo(() => {
    if (!result) return null;
    const lastWeekTotal = result.data.reduce(
      (acc: number, r: any) => acc + Number(r.Last_Week_Sales || 0),
      0
    );
    const forecastTotal = result.data.reduce((acc: number, r: any) => {
      const arr = Array.isArray(r.Final_Forecasted_Sales)
        ? r.Final_Forecasted_Sales
        : [];
      const total = arr.reduce((a: number, b: number) => a + Number(b || 0), 0);
      return acc + total;
    }, 0);
    const avgWeeklyForecast = forecastTotal / (result.horizon || 1);
    const avgWeeklyGrowth =
      lastWeekTotal > 0
        ? (avgWeeklyForecast / lastWeekTotal - 1) * 100
        : 0;

    const catMap = new Map<string, { products: number; total: number }>();
    result.data.forEach((r: any) => {
      const category = r.Category ?? "Unknown";
      const arr = Array.isArray(r.Final_Forecasted_Sales)
        ? r.Final_Forecasted_Sales
        : [];
      const total = arr.reduce((a: number, b: number) => a + Number(b || 0), 0);
      const entry = catMap.get(category) || { products: 0, total: 0 };
      entry.products += 1;
      entry.total += total;
      catMap.set(category, entry);
    });
    const categories = Array.from(catMap.entries()).map(([category, v]) => ({
      category,
      products: v.products,
      total: v.total,
      avgPerProduct: v.products ? Math.round(v.total / v.products) : 0,
    }));
    return { lastWeekTotal, forecastTotal, avgWeeklyGrowth, categories };
  }, [result]);

  const runForecast = async () => {
    if (!file || !token) return;
    setLoading(true);
    setError(null);
    setResult(null);
    setAlerts(null);
    try {
      const res = await apiForecast(token, file, horizon);
      setResult(res);
      setActiveTab("results");
      // Fetch alerts generated by backend side-effect
      const alertsRes = await getAlerts(token);
      setAlerts(alertsRes.data || []);
    } catch (err: any) {
      setError(err.message || "Forecast failed");
    } finally {
      setLoading(false);
    }
  };

  const download = async () => {
    if (!file || !token) return;
    try {
      const blob = await downloadCsv(token, file, horizon);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `niyojan_forecast_${horizon}w.csv`;
      a.click();
      window.URL.revokeObjectURL(url);
    } catch (err: any) {
      setError(err.message || "Download failed");
    }
  };

  const generateReport = async () => {
    if (!token) return;
    setReportLoading(true);
    try {
      const res = await getReport(token);
      setReport(res.report || "");
    } catch (err: any) {
      setError(err.message || "Report generation failed");
    } finally {
      setReportLoading(false);
    }
  };

  return (
    <Layout>
      <div className="card">
        <h2>Upload data and forecast</h2>
        <div className="grid">
          <label>
            CSV file
            <input
              type="file"
              accept=".csv"
              onChange={(e) => setFile(e.target.files?.[0] || null)}
            />
          </label>
          <label>
            Horizon (weeks)
            <input
              type="number"
              min={1}
              max={12}
              value={horizon}
              onChange={(e) =>
                setHorizon(parseInt(e.target.value || "4"))
              }
            />
          </label>
        </div>
        <div className="row">
          <button disabled={!file || loading} onClick={runForecast}>
            Run forecast
          </button>
          <button
            className="ghost"
            disabled={!result || loading || !file}
            onClick={download}
          >
            Download CSV
          </button>
        </div>
        {error && (
          <div className="error" style={{ marginTop: 12 }}>
            {error}
          </div>
        )}
      </div>

      {loading && (
        <div className="card">
          <div>Running forecast...</div>
        </div>
      )}

      {overview && (
        <div className="card">
          <h2>Forecast Overview</h2>
          <div className="stats">
            <div className="stat">
              <div className="label">Total Last Week Sales</div>
              <div className="value">
                {overview.lastWeekTotal.toLocaleString()} units
              </div>
            </div>
            <div className="stat">
              <div className="label">
                Total {result.horizon}-Week Forecast
              </div>
              <div className="value">
                {overview.forecastTotal.toLocaleString()} units
              </div>
            </div>
            <div className="stat">
              <div className="label">Avg Weekly Growth</div>
              <div className="value">
                {overview.avgWeeklyGrowth.toFixed(1)}%
              </div>
            </div>
          </div>
        </div>
      )}

      {overview && (
        <div className="card">
          <h2>Category-wise Forecast</h2>
          <div className="table">
            <table>
              <thead>
                <tr>
                  <th>Category</th>
                  <th>Products</th>
                  <th>Total_Forecast</th>
                  <th>Avg_per_Product</th>
                </tr>
              </thead>
              <tbody>
                {overview.categories.map((c: any, idx: number) => (
                  <tr key={idx}>
                    <td>{c.category}</td>
                    <td>{c.products}</td>
                    <td>{c.total}</td>
                    <td>{c.avgPerProduct}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {result && (
        <div className="card">
          <div className="tabs">
            <button
              className={`tab ${activeTab === "results" ? "active" : ""}`}
              onClick={() => setActiveTab("results")}
            >
              Results
            </button>
            <button
              className={`tab ${activeTab === "alerts" ? "active" : ""}`}
              onClick={() => setActiveTab("alerts")}
            >
              Alerts
            </button>
            <button
              className={`tab ${activeTab === "report" ? "active" : ""}`}
              onClick={() => setActiveTab("report")}
            >
              Report
            </button>
          </div>

          {activeTab === "results" && (
            <>
              <h2>Results</h2>
              <div className="metrics">
                <div className="metric">
                  <div className="label">Products</div>
                  <div className="value">{result.products}</div>
                </div>
                <div className="metric">
                  <div className="label">Horizon</div>
                  <div className="value">{result.horizon} weeks</div>
                </div>
              </div>
              <div className="table">
                <table>
                  <thead>
                    <tr>
                      <th>Product_ID</th>
                      <th>Name</th>
                      <th>Category</th>
                      <th>Last_Week</th>
                      <th>Last_Week_Sales</th>
                      {Array.from({ length: result.horizon }).map((_, i) => (
                        <th key={i}>Week_{i + 1}_Final</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {result.data.map((r: any) => (
                      <tr key={r.Product_ID}>
                        <td>{r.Product_ID}</td>
                        <td>{r.Product_Name}</td>
                        <td>{r.Category}</td>
                        <td>{r.Last_Week}</td>
                        <td>{r.Last_Week_Sales}</td>
                        {r.Final_Forecasted_Sales.map(
                          (v: number, idx: number) => (
                            <td key={idx}>{v}</td>
                          )
                        )}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {/* 📊 Add Chart Here */}
              {result.data && result.data.length > 0 && (
                <ForecastChart data={result.data} />
              )}

              <div className="row" style={{ marginTop: 12 }}>
                <button
                  className="ghost"
                  disabled={!result || loading || !file}
                  onClick={download}
                >
                  Download CSV
                </button>
              </div>
            </>
          )}

          {activeTab === "alerts" && (
            <>
              <h2>Alerts</h2>
              {alerts && alerts.length > 0 ? (
                <div className="table">
                  <table>
                    <thead>
                      <tr>
                        <th>Product</th>
                        <th>Forecast</th>
                        <th>Alert</th>
                        <th>Created</th>
                      </tr>
                    </thead>
                    <tbody>
                      {alerts.map((a, idx) => {
                        // Match alert product with forecast result
                        const productInfo = result?.data?.find(
                          (r: any) => r.Product_ID === a.product
                        );
                        const productName = productInfo?.Product_Name || a.product;
                        const productId = a.product;

                        // Replace product ID in alert message with "Name (ID)"
                        let alertMsg = a.alert;
                        if (alertMsg.includes(productId)) {
                          alertMsg = alertMsg.replace(
                            productId,
                            `${productName} (${productId})`
                          );
                        }

                        // Determine color style for alert text
                        let alertStyle: React.CSSProperties = { color: "#fff" };
                        if (/high demand/i.test(alertMsg)) {
                          alertStyle = { color: "#f87171", fontWeight: 600 }; // red
                        } else if (/balanced/i.test(alertMsg)) {
                          alertStyle = { color: "#4ade80", fontWeight: 600 }; // green
                        } else if (/low stock/i.test(alertMsg) || /restock/i.test(alertMsg)) {
                          alertStyle = { color: "#fbbf24", fontWeight: 600 }; // orange/yellow
                        }

                        return (
                          <tr key={idx}>
                            <td>
                              {productName} ({productId})
                            </td>
                            <td>{a.forecast ?? "n/a"}</td>
                            <td style={alertStyle}>{alertMsg}</td>
                            <td>{a.created_at}</td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              ) : (
                <div>No alerts yet</div>
              )}
            </>
          )}



          {activeTab === "report" && (
            <>
              <h2>📊 AI Forecast Report</h2>
              <div className="row" style={{ gap: "8px", marginBottom: "12px" }}>
                <button
                  onClick={() =>
                    window.open(`${import.meta.env.VITE_API_BASE || "http://localhost:8000"}/report/view?token=${token}`, "_blank")
                  }
                >
                  🔍 View Report
                </button>

                <button
                  className="ghost"
                  onClick={() => {
                    const link = document.createElement("a");
                    link.href = `${import.meta.env.VITE_API_BASE || "http://localhost:8000"}/report/download?token=${token}`;
                    link.setAttribute("download", "Niyojan_Forecast_Report.pdf");
                    document.body.appendChild(link);
                    link.click();
                    link.remove();
                  }}
                >
                  ⬇️ Download Report
                </button>
              </div>

              {/* Inline PDF Preview */}
              <div
                style={{
                  marginTop: "16px",
                  border: "1px solid #ccc",
                  borderRadius: "8px",
                  overflow: "hidden",
                  height: "600px",
                }}
              >
                <iframe
                  src={`${import.meta.env.VITE_API_BASE || "http://localhost:8000"}/report/view?token=${token}`}
                  title="Niyojan Forecast Report"
                  style={{ width: "100%", height: "100%", border: "none" }}
                ></iframe>
              </div>

              {/* Email Sending Section */}
              <div className="row" style={{ marginTop: "20px" }}>
                <input
                  type="email"
                  placeholder="Enter recipient email (admin only)"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  style={{
                    flex: 1,
                    padding: "8px",
                    borderRadius: "4px",
                    border: "1px solid #ccc",
                  }}
                />
                <button
                  onClick={async () => {
                    if (!email) return alert("Please enter an email address");
                    try {
                      const res = await fetch(
                        `${import.meta.env.VITE_API_BASE || "http://localhost:8000"}/send-report`,
                        {
                          method: "POST",
                          headers: {
                            "Content-Type": "application/json",
                            Authorization: `Bearer ${token}`,
                          },
                          body: JSON.stringify({ recipients: [email] }),
                        }
                      );
                      if (res.ok) {
                        alert(`✅ Report sent successfully to ${email}`);
                        setEmail("");
                      } else {
                        const data = await res.json();
                        alert(`❌ Failed: ${data.detail || "Server error"}`);
                      }
                    } catch (err) {
                      console.error(err);
                      alert("Network error while sending email");
                    }
                  }}
                >
                  📧 Send Report
                </button>
              </div>
            </>
          )}
        </div>
      )}
    </Layout>
  );
}
